const actionsTypes = {
    ADICIONAR_PEDIDO: 'ADICIONAR_PEDIDO',
    REMOVER_PEDIDO: 'REMOVER_PEDIDO',
    PEDIDO_SELECIONADO: 'PEDIDO_SELECIONADO',
    LISTAR_PEDIDOS: 'LISTAR_PEDIDOS',
    EDITAR_PEDIDO: 'EDITAR_PEDIDO',
    ATUALIZAR_PEDIDO: 'ATUALIZAR_PEDIDO',
};

export { actionsTypes };